---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/vertexridgegh/public_html
    - npm install
    - npm run build
    - /bin/cp -r .next/standalone/. $DEPLOYPATH/
    - /bin/cp -r public $DEPLOYPATH/public
    - /bin/cp app.js $DEPLOYPATH/app.js
