---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vertexridgegh/public_html
    - yarn install
    - yarn build
    - /bin/cp -r .next/standalone/* $DEPLOYPATH
    - /bin/cp -r .next/static $DEPLOYPATH/.next/
    - /bin/cp -r public $DEPLOYPATH
